### ISSUE TITLE
Make it responsive

### ISSUE THREAD

**Issue by akhileshthite** [AkhileshThite/Portfolio#1]
There are 2 html pages 
```
index.html
about.html
```
Main css file in static folder contains dynamic star animations
```
style.css
```

**Comment by ghost** [comment]
I would like to work on this

**Comment by AkhileshThite** [comment]
> I would like to work on this

Great! assigned :)

**Comment by akhileshthite** [comment]
> I would like to work on this

Great! assigned :)
