### ISSUE TITLE
Footer is not fixed at the bottom in mobile view

### ISSUE THREAD

**Issue by akhileshthite** [AkhileshThite/Portfolio#6]
Problem in:- Index.html, projects.html, about.html

![Screenshot 2021-06-02 at 11 25 13 AM](https://user-images.githubusercontent.com/68826419/120430970-71b28380-c395-11eb-99cc-e1ae91758bb4.png)

**Comment by Glenn-Mendonca** [comment]
Where do u want it to be? The extreme bottom or below your projects?

**Comment by akhileshthite** [comment]
> Where do u want it to be? The extreme bottom or below your projects?

At the extreme bottom for projects.html.
Also for index.html and about.html, it is not fixed at the bottom in mobile view, try to fix that also.

**Comment by Glenn-Mendonca** [comment]
@Skyhero-admin  told me to remove the extra space  below projects in mobile view. Should I do it?

**Comment by akhileshthite** [comment]
> @Skyhero-admin told me to remove the extra space below projects in mobile view. Should I do it?

Okay, but make sure it scrolls down and covers all the projects in mobile view.
